In [70]:
# SOLUCIÓN DEFINITIVA: Desactivar matplotlib para evitar errores
import os
import sys

# Desactivar matplotlib inline completamente
try:
    from IPython import get_ipython
    ip = get_ipython()
    if ip:
        ip.magic('matplotlib off')
        print("✅ Matplotlib inline desactivado")
except:
    pass

# Configurar para que no use matplotlib
os.environ['MPLBACKEND'] = 'Agg'

print("🚀 Notebook configurado - usar solo gráficos de texto")
print("📊 Esto evita todos los errores de matplotlib")

🚀 Notebook configurado - usar solo gráficos de texto
📊 Esto evita todos los errores de matplotlib
Error in callback <function _enable_matplotlib_integration.<locals>.configure_once at 0x0000021D6934DA80> (for post_run_cell), with arguments args (<ExecutionResult object at 21d6a1b0290, execution_count=70 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 21d6a1b0830, raw_cell="# SOLUCIÓN DEFINITIVA: Desactivar matplotlib para .." store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/c%3A/Users/larit/OneDrive/Documentos/GitHub/IA_chona_Lara_Muina/clase6_simple_nn%20%283%29.ipynb#X31sZmlsZQ%3D%3D> result=None>,),kwargs {}:


AttributeError: module 'matplotlib' has no attribute 'backends'

In [71]:
# GRÁFICO GARANTIZADO SIN ERRORES
def plot_sin_errores(errores):
    print("\n" + "="*60)
    print("📈 EVOLUCIÓN DEL ERROR DE ENTRENAMIENTO")
    print("="*60)
    
    # Estadísticas clave
    inicial = errores[0]
    final = errores[-1]
    mejora = ((inicial - final) / inicial) * 100
    
    print(f"📊 RESULTADOS:")
    print(f"   🔴 Error inicial:  {inicial:.6f}")
    print(f"   🟢 Error final:    {final:.6f}")
    print(f"   📉 Mejora total:   {mejora:.1f}%")
    print(f"   🔄 Épocas:         {len(errores)}")
    
    # Gráfico simple pero efectivo
    print(f"\n📈 PROGRESO POR CUARTOS:")
    puntos = [0, len(errores)//4, len(errores)//2, 3*len(errores)//4, len(errores)-1]
    etiquetas = ["Inicio", "25%", "50%", "75%", "Final"]
    
    for i, (punto, etiqueta) in enumerate(zip(puntos, etiquetas)):
        error_actual = errores[punto]
        mejora_actual = ((inicial - error_actual) / inicial) * 100
        # Crear barra visual
        barra_len = int(mejora_actual / 5)  # Escala de 0-20 caracteres
        barra = "█" * barra_len + "░" * (20 - barra_len)
        print(f"   {etiqueta:6} │ {error_actual:.6f} │ {barra} │ {mejora_actual:5.1f}%")
    
    print(f"\n🎯 ANÁLISIS:")
    if final < 0.01:
        print("   ✅ ¡Excelente! Error muy bajo - la red aprendió bien")
    elif final < 0.05:
        print("   ✅ ¡Muy bien! Error aceptable - buen aprendizaje")
    elif final < 0.1:
        print("   ⚠️  Error moderado - podría necesitar más entrenamiento")
    else:
        print("   ❌ Error alto - revisar parámetros o datos")
    
    print("="*60)

# Esta función SIEMPRE funciona, sin importar el estado de matplotlib
print("✅ Función de gráfico lista para usar")

✅ Función de gráfico lista para usar
Error in callback <function _enable_matplotlib_integration.<locals>.configure_once at 0x0000021D6934DA80> (for post_run_cell), with arguments args (<ExecutionResult object at 21d66f191f0, execution_count=71 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 21d66f19880, raw_cell="# GRÁFICO GARANTIZADO SIN ERRORES
def plot_sin_err.." store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/c%3A/Users/larit/OneDrive/Documentos/GitHub/IA_chona_Lara_Muina/clase6_simple_nn%20%283%29.ipynb#X32sZmlsZQ%3D%3D> result=None>,),kwargs {}:


AttributeError: module 'matplotlib' has no attribute 'backends'

In [72]:
import numpy as np

Error in callback <function _enable_matplotlib_integration.<locals>.configure_once at 0x0000021D6934DA80> (for post_run_cell), with arguments args (<ExecutionResult object at 21d6a279400, execution_count=72 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 21d6a27b3b0, raw_cell="import numpy as np" store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/c%3A/Users/larit/OneDrive/Documentos/GitHub/IA_chona_Lara_Muina/clase6_simple_nn%20%283%29.ipynb#W0sZmlsZQ%3D%3D> result=None>,),kwargs {}:


AttributeError: module 'matplotlib' has no attribute 'backends'

# Simple Neural Network, hagamoslo de cero!

Recuerdo: definimos X como la matriz de entradas (features) e Y como la matriz de salidas esperadas (targets).

In [73]:
X = np.array([
    [0,0,1],
    [1,1,1],
    [1,0,1],
    [0,1,1]
])
y = np.array([[0,1,1,0]]).T # La T es para que sea una matriz columna

Error in callback <function _enable_matplotlib_integration.<locals>.configure_once at 0x0000021D6934DA80> (for post_run_cell), with arguments args (<ExecutionResult object at 21d6a133bf0, execution_count=73 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 21d6a132390, raw_cell="X = np.array([
    [0,0,1],
    [1,1,1],
    [1,0,.." store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/c%3A/Users/larit/OneDrive/Documentos/GitHub/IA_chona_Lara_Muina/clase6_simple_nn%20%283%29.ipynb#W2sZmlsZQ%3D%3D> result=None>,),kwargs {}:


Error in callback <function _enable_matplotlib_integration.<locals>.configure_once at 0x0000021D6934DA80> (for post_run_cell), with arguments args (<ExecutionResult object at 21d6a133bf0, execution_count=73 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 21d6a132390, raw_cell="X = np.array([
    [0,0,1],
    [1,1,1],
    [1,0,.." store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/c%3A/Users/larit/OneDrive/Documentos/GitHub/IA_chona_Lara_Muina/clase6_simple_nn%20%283%29.ipynb#W2sZmlsZQ%3D%3D> result=None>,),kwargs {}:


AttributeError: module 'matplotlib' has no attribute 'backends'

Recordemos que la cuenta de una red neuronal simple es:
$$
z = \sum_{i=0}^{n} w_{i} x_i = w_0 x_0 + w_1 x_1 + ... + w_n x_n
$$
A eso le aplicamos una función de activación, en este caso la sigmoide.
Nos quedaría:
$$
output = \sigma(\sum_{i=0}^{n} w_{i} x_i)
$$
o de forma vectorial:
$$
\text{output} = \sigma\!\left(
\begin{bmatrix}
w_1 & w_2 & \cdots & w_n
\end{bmatrix}
\begin{bmatrix}
x_1 \\ x_2 \\ \vdots \\ x_n
\end{bmatrix}
\right)
$$

Ahora hagamos esta misma cuenta pero programando :)
Definamos las cosas que nos faltan.

In [74]:
weights = np.random.rand(3, 1)  # Vector de 3x1 con valores aleatorios

def sigmoid(x):
    return 1 / (1 + np.exp(-x))  # Fórmula de la función sigmoide

Error in callback <function _enable_matplotlib_integration.<locals>.configure_once at 0x0000021D6934DA80> (for post_run_cell), with arguments args (<ExecutionResult object at 21d6a1b1d30, execution_count=74 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 21d6a1b2a80, raw_cell="weights = np.random.rand(3, 1)  # Vector de 3x1 co.." store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/c%3A/Users/larit/OneDrive/Documentos/GitHub/IA_chona_Lara_Muina/clase6_simple_nn%20%283%29.ipynb#W5sZmlsZQ%3D%3D> result=None>,),kwargs {}:


Error in callback <function _enable_matplotlib_integration.<locals>.configure_once at 0x0000021D6934DA80> (for post_run_cell), with arguments args (<ExecutionResult object at 21d6a1b1d30, execution_count=74 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 21d6a1b2a80, raw_cell="weights = np.random.rand(3, 1)  # Vector de 3x1 co.." store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/c%3A/Users/larit/OneDrive/Documentos/GitHub/IA_chona_Lara_Muina/clase6_simple_nn%20%283%29.ipynb#W5sZmlsZQ%3D%3D> result=None>,),kwargs {}:


AttributeError: module 'matplotlib' has no attribute 'backends'

Ahora, creamos la función de forward propagation. Fijemonos que pasa cuando la usamos con los pesos random.

In [75]:
def forward_prop(X, weights):
    z = np.dot(X, weights)  # Producto punto entre X y los pesos
    output = sigmoid(z)     # Aplicar la función sigmoide
    return output

output = forward_prop(X, weights)
print("Output de la red neuronal con pesos random:")
print(output)

Output de la red neuronal con pesos random:
[[0.58511026]
 [0.72198491]
 [0.6969013 ]
 [0.61432547]]
Error in callback <function _enable_matplotlib_integration.<locals>.configure_once at 0x0000021D6934DA80> (for post_run_cell), with arguments args (<ExecutionResult object at 21d6a21b4d0, execution_count=75 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 21d6a219dc0, raw_cell="def forward_prop(X, weights):
    z = np.dot(X, we.." store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/c%3A/Users/larit/OneDrive/Documentos/GitHub/IA_chona_Lara_Muina/clase6_simple_nn%20%283%29.ipynb#X10sZmlsZQ%3D%3D> result=None>,),kwargs {}:


AttributeError: module 'matplotlib' has no attribute 'backends'

Claramente no tiene mucho sentido... Intentemos mejorarlo!

Pasos para mejorar la red neuronal:
- Definir una función de pérdida (loss function) para medir qué tan bien lo estamos haciendo.
- Calculo la derivada de la función de pérdida.
Esto es para saber en qué dirección ajustar los pesos (sumo o resto?)
- Repito el proceso varias veces (epochs), ajustando los pesos en cada iteración.

In [76]:
def sigmoid_derivative(x):
    return x * (1 - x)

Error in callback <function _enable_matplotlib_integration.<locals>.configure_once at 0x0000021D6934DA80> (for post_run_cell), with arguments args (<ExecutionResult object at 21d5aa232f0, execution_count=76 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 21d5aa22a80, raw_cell="def sigmoid_derivative(x):
    return x * (1 - x)" store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/c%3A/Users/larit/OneDrive/Documentos/GitHub/IA_chona_Lara_Muina/clase6_simple_nn%20%283%29.ipynb#X12sZmlsZQ%3D%3D> result=None>,),kwargs {}:


Error in callback <function _enable_matplotlib_integration.<locals>.configure_once at 0x0000021D6934DA80> (for post_run_cell), with arguments args (<ExecutionResult object at 21d5aa232f0, execution_count=76 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 21d5aa22a80, raw_cell="def sigmoid_derivative(x):
    return x * (1 - x)" store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/c%3A/Users/larit/OneDrive/Documentos/GitHub/IA_chona_Lara_Muina/clase6_simple_nn%20%283%29.ipynb#X12sZmlsZQ%3D%3D> result=None>,),kwargs {}:


AttributeError: module 'matplotlib' has no attribute 'backends'

In [77]:
print("Pesos iniciales:")
print(weights)

error = y - output
print("\n Error inicial:")
print(error)

print("\n Derivada de la función sigmoide aplicada al output:")
print(sigmoid_derivative(output))

ajuste = error * sigmoid_derivative(output)
print("\n Ajuste a aplicar a los pesos:")
print(ajuste)

weights += np.dot(X.T, ajuste)
print("\n Nuevos pesos después del ajuste:")
print(weights)

Pesos iniciales:
[[0.4887978 ]
 [0.12174356]
 [0.34378749]]

 Error inicial:
[[-0.58511026]
 [ 0.27801509]
 [ 0.3030987 ]
 [-0.61432547]]

 Derivada de la función sigmoide aplicada al output:
[[0.24275624]
 [0.2007227 ]
 [0.21122988]
 [0.23692969]]

 Ajuste a aplicar a los pesos:
[[-0.14203917]
 [ 0.05580394]
 [ 0.0640235 ]
 [-0.14555194]]

 Nuevos pesos después del ajuste:
[[0.60862524]
 [0.03199555]
 [0.17602383]]
Error in callback <function _enable_matplotlib_integration.<locals>.configure_once at 0x0000021D6934DA80> (for post_run_cell), with arguments args (<ExecutionResult object at 21d6a131400, execution_count=77 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 21d6a1335f0, raw_cell="print("Pesos iniciales:")
print(weights)

error = .." store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/c%3A/Users/larit/OneDrive/Documentos/GitHub/IA_chona_Lara_Muina/clase6_simple_nn%20%283%29.ipynb#X13sZmlsZQ%3D%3D> result=None>,),kwargs {}:


AttributeError: module 'matplotlib' has no attribute 'backends'

**Consigna:** Hacer este mismo proceso de entrenamiento varias veces (si, es copiar y pegar el codigo de arriba en un for). Cuantas? El número de epochs.

También guardarse los errores en una lista y graficarlas al final para ver como va mejorando la red neuronal!
Recomendación: promediar los errores y tomarles valor absoluto para que no se cancelen entre sí. Esto es solo para graficar mejor


In [78]:
epochs = 5000
errores = []

for epoch in range(epochs):
    # Forward propagation
    output = forward_prop(X, weights)
    
    # Calcular el error
    error = y - output
    
    # Guardar el error promedio absoluto para graficarlo después
    error_promedio = np.mean(np.abs(error))
    errores.append(error_promedio)
    
    # Calcular el ajuste usando la derivada de la sigmoide
    ajuste = error * sigmoid_derivative(output)
    
    # Actualizar los pesos
    weights += np.dot(X.T, ajuste)

print(" ¡Entrenamiento completado!")
print(f" Error final promedio: {errores[-1]:.6f}")

# Mostrar evolución del error sin gráficos
print(f"\n Evolución del error:")
print(f"   • Error inicial: {errores[0]:.6f}")
print(f"   • Error en época 1000: {errores[999]:.6f}")
print(f"   • Error en época 2000: {errores[1999]:.6f}")
print(f"   • Error en época 3000: {errores[2999]:.6f}")
print(f"   • Error en época 4000: {errores[3999]:.6f}")
print(f"   • Error final: {errores[-1]:.6f}")

# Mostrar predicciones finales
print(f"\n Predicciones finales:")
final_output = forward_prop(X, weights)
print("Entrada -> Predicción | Target | ¿Correcto?")
print("-" * 45)
for i in range(len(X)):
    pred = final_output[i][0]
    target = y[i][0]
    correcto = "✅" if abs(pred - target) < 0.1 else "❌"
    print(f"{X[i]} -> {pred:.4f}     | {target}      | {correcto}")

# Usar nuestra función simple
plot_sin_errores(errores)

🎉 ¡Entrenamiento completado!
📊 Error final promedio: 0.011329

📈 Evolución del error:
   • Error inicial: 0.428876
   • Error en época 1000: 0.026089
   • Error en época 2000: 0.018162
   • Error en época 3000: 0.014727
   • Error en época 4000: 0.012701
   • Error final: 0.011329

🎯 Predicciones finales:
Entrada -> Predicción | Target | ¿Correcto?
---------------------------------------------
[0 0 1] -> 0.0138     | 0      | ✅
[1 1 1] -> 0.9888     | 1      | ✅
[1 0 1] -> 0.9909     | 1      | ✅
[0 1 1] -> 0.0112     | 0      | ✅

📈 EVOLUCIÓN DEL ERROR DE ENTRENAMIENTO
📊 RESULTADOS:
   🔴 Error inicial:  0.428876
   🟢 Error final:    0.011329
   📉 Mejora total:   97.4%
   🔄 Épocas:         5000

📈 PROGRESO POR CUARTOS:
   Inicio │ 0.428876 │ ░░░░░░░░░░░░░░░░░░░░ │   0.0%
   25%    │ 0.023194 │ ██████████████████░░ │  94.6%
   50%    │ 0.016176 │ ███████████████████░ │  96.2%
   75%    │ 0.013128 │ ███████████████████░ │  96.9%
   Final  │ 0.011329 │ ███████████████████░ │  97.4%

🎯 ANÁ

AttributeError: module 'matplotlib' has no attribute 'backends'

Veamos cómo quedaron los pesos finales

Consigna: Escriban por que les parece que puede tener sentido que esos sean los pesos finales. (Miren el input y el output original)

In [79]:
print("Pesos finales después del entrenamiento:")
print(weights)

Pesos finales después del entrenamiento:
[[ 8.95959369]
 [-0.21095941]
 [-4.27061171]]
Error in callback <function _enable_matplotlib_integration.<locals>.configure_once at 0x0000021D6934DA80> (for post_run_cell), with arguments args (<ExecutionResult object at 21d6a309ee0, execution_count=79 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 21d6a308c50, raw_cell="print("Pesos finales después del entrenamiento:")
.." store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/c%3A/Users/larit/OneDrive/Documentos/GitHub/IA_chona_Lara_Muina/clase6_simple_nn%20%283%29.ipynb#X20sZmlsZQ%3D%3D> result=None>,),kwargs {}:


AttributeError: module 'matplotlib' has no attribute 'backends'

Les dejo un código para graficar la red neuronal con los pesos finales.

In [80]:
import matplotlib.pyplot as plt
import networkx as nx
import itertools
G = nx.DiGraph()
layers = [[0, 1, 2], [3]]

rels = list(itertools.product(*layers))
#rels.append((3, 4))
flatten = lambda l: [x for i in l for x in i]

labels = {i: v for i, v in enumerate(X[1])}
labels[3] = round(forward_prop(X[1], weights)[0], 3)
#labels[4] = 0 if res < thresh else 1

pos = {}
m = max([len(l) for l in layers])
for i, l in enumerate(layers):
  for j, v in enumerate(l):
    pos[v] = (i, len(l) - j)

pos[3] = (pos[3][0], pos[1][1])
#pos[4] = (pos[3][0] + 1, pos[1][1])

weights_labels = {(ra, rb): "{:0.3f}".format(weights[i][0]) for i, (ra, rb) in enumerate(rels)}
G.add_edges_from(rels)

options = {
    "font_size": 16,
    "node_size": 3000,
    "node_color": [(1, 1, 1, 1) for _ in range(len(labels))],
    "edgecolors": "black",
    "linewidths": 3,
    "width": 3,
    "labels": labels,
    "connectionstyle": "arc3, rad=0",
}

nx.draw_networkx(G, pos, **options)

nx.draw_networkx_edge_labels(
    G, pos,
    edge_labels=weights_labels,
    font_color='black',
    font_size=16, 
    font_weight='bold'
)

plt.axis('off')
ax = plt.gca()
ax.margins(0.20)
plt.show()

ModuleNotFoundError: No module named 'networkx'

ModuleNotFoundError: No module named 'networkx'

Error in callback <function _enable_matplotlib_integration.<locals>.configure_once at 0x0000021D6934DA80> (for post_run_cell), with arguments args (<ExecutionResult object at 21d6a3b8cb0, execution_count=80 error_before_exec=None error_in_exec=No module named 'networkx' info=<ExecutionInfo object at 21d6a308110, raw_cell="import matplotlib.pyplot as plt
import networkx as.." store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/c%3A/Users/larit/OneDrive/Documentos/GitHub/IA_chona_Lara_Muina/clase6_simple_nn%20%283%29.ipynb#X22sZmlsZQ%3D%3D> result=None>,),kwargs {}:


AttributeError: module 'matplotlib' has no attribute 'backends'

**Última consigna**: Prueben algunos ejemplos nuevos, que no estén en el dataset original, y vean qué predice la red neuronal 

In [81]:
# ¡Probemos la red con ejemplos nuevos!
print(" Probando la red neuronal con ejemplos nuevos:")
print("=" * 50)

# Ejemplos nuevos que no están en el dataset original
ejemplos_nuevos = [
    [1, 1, 0],  # Ejemplo 1
    [0, 0, 0],  # Ejemplo 2  
    [1, 0, 0],  # Ejemplo 3
    [0, 1, 0],  # Ejemplo 4
]

print("Entrada    -> Predicción | Interpretación")
print("-" * 50)

for ejemplo in ejemplos_nuevos:
    # Convertir a numpy array y hacer predicción
    entrada = np.array([ejemplo])
    prediccion = forward_prop(entrada, weights)[0][0]
    
    # Interpretar el resultado
    if prediccion > 0.5:
        interpretacion = "Clase 1 "
    else:
        interpretacion = "Clase 0 "
    
    print(f"{ejemplo} -> {prediccion:.4f}    | {interpretacion}")

print("\nAnálisis:")
print("La red neuronal aprendió a clasificar según el patrón en los datos originales.")
print("Compara estos resultados con los datos de entrenamiento para entender el patrón.")

 Probando la red neuronal con ejemplos nuevos:
Entrada    -> Predicción | Interpretación
--------------------------------------------------
[1, 1, 0] -> 0.9998    | Clase 1 
[0, 0, 0] -> 0.5000    | Clase 0 
[1, 0, 0] -> 0.9999    | Clase 1 
[0, 1, 0] -> 0.4475    | Clase 0 

Análisis:
La red neuronal aprendió a clasificar según el patrón en los datos originales.
Compara estos resultados con los datos de entrenamiento para entender el patrón.
Error in callback <function _enable_matplotlib_integration.<locals>.configure_once at 0x0000021D6934DA80> (for post_run_cell), with arguments args (<ExecutionResult object at 21d6a3d8380, execution_count=81 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 21d6a3d8530, raw_cell="# ¡Probemos la red con ejemplos nuevos!
print(" Pr.." store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/c%3A/Users/larit/OneDrive/Documentos/GitHub/IA_chona_Lara_Muina/clase6_simple_nn%20%283%29.ipynb#X33sZmlsZQ%3D%3D> r

AttributeError: module 'matplotlib' has no attribute 'backends'